### ISSUE TITLE
Issue when executing `npm run ios`

### ISSUE THREAD

**Issue by ignaciolarranaga** [holepunchto/bare-expo#7]
Some idea?

This is what I'm getting:
```
npm run ios        

> ios
> expo run:ios

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: /bin/bash -c 
set -e
node ios/link

/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-module-resolve/index.js:285
  throw errors.PACKAGE_PATH_NOT_EXPORTED(`Package subpath '${subpath}' is not defined by "exports" in '${packageURL}'`)
               ^

ModuleResolveError: PACKAGE_PATH_NOT_EXPORTED: Package subpath './package' is not defined by "exports" in 'file:///Users/ignacio/Workspaces/Pear/bare-expo/node_modules/expo-constants/package.json'
    at exports.packageExports (/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-module-resolve/index.js:285:16)
    at exports.packageExports.next (<anonymous>)
    at exports.package (/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-module-resolve/index.js:188:32)
    at exports.package.next (<anonymous>)
    at exports.module (/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-module-resolve/index.js:98:26)
    at exports.module.next (<anonymous>)
    at [Symbol.asyncIterator] (/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-module-resolve/index.js:41:28)
    at async dependencies (/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-link/lib/dependencies.js:7:22)
    at async link (/Users/ignacio/Workspaces/Pear/bare-expo/node_modules/bare-link/index.js:59:20) {
  code: 'PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.17.0


pod install --repo-update --ansi exited with non-zero code: 1
```

**Comment by supersuryaansh** [comment]
Can you delete the iOS directory and retry?

**Comment by kasperisager** [comment]
I'm seeing the same thing after an `npm up`.
